### ISSUE TITLE
Timer or clock issue

### ISSUE THREAD

**Issue by gjongenelen** [whitecatboard/Lua-RTOS-ESP32#116]
Hello,

I need a smaller interval than 500us, which is the max currently supported by the hardware timer.

Is this a hardware limitation?

**Comment by thunderWhitecat** [comment]
Hi @gjongenelen,

Can you be more precise?
From Lua, which Lua module, from C?

**Comment by gjongenelen** [comment]
In the file: https://github.com/whitecatboard/Lua-RTOS-ESP32/blob/master/components/lua/modules/sys/tmr.c

`181	if (micros < 500) {`
`182		return luaL_exception(L, TIMER_ERR_INVALID_PERIOD);`
`183	}`

What is the reason behind this?

**Comment by thunderWhitecat** [comment]
Hi @gjongenelen,

Running ESP32 at 240 Mhz each instruction takes 4.166666666 nanoseconds, so in 1 microsecond you can run 240 instructions.

In previous tests, configuring a hardware timer at 1 microsecond starves the CPU and the switching context is not possible. To avoid this, I put a sanity check into the tmr_setup function in drivers/timer.c to avoid to configure timers at periods lower than 5 microseconds. In the Lua module I set this restriction to 500 microseconds, but this value was arbitrary and probably we can put a lower value.

Please, if you have time, you can play with lower values in the Lua module, and share with us the results to put a more suitable restriction to this value.

**Comment by thunderWhitecat** [comment]
Hi @gjongenelen,

Any progress on this issue?

**Comment by gjongenelen** [comment]
Not really, I tried tuning the minimum down to 200us. But for my use-case the process of each timer was too long to be able to finish before the new timer was fired off. 

I don't think the micros value is a real limit tho. Just not suitable for my use-case.

**Comment by thunderWhitecat** [comment]
HW timer generates an interrupt when timer has expired (alarm). To call the Lua callback we must first to queue the alarm into a FreeRTOS queue, and then process the interrupt outside the interrupt in a task. It is not possible to execute the callback inside the isr because:

* All the execution thread must be in IRAM
* We have not enough space in the isr stack

This technique is know as deferred interrupt processing.

You can also play increasing the priority for the alarm task in sys/drivers/timer.c:

xReturn = xTaskCreatePinnedToCore(alarm_task, "tmral", CONFIG_LUA_RTOS_LUA_THREAD_STACK_SIZE, NULL, CONFIG_LUA_RTOS_LUA_THREAD_PRIORITY, &tmr->task, xPortGetCoreID());

Increasing this priority can help to ensure that the callback is called just after the ISR ends.

You can also try to disable LUA_USE_LUA_LOCK in luaconf.h:

change

#define LUA_USE_LUA_LOCK 1

to

#define LUA_USE_LUA_LOCK 0

You can also send us information about what you are doing into the timer callback to have a better idea and try to find a solution: source code, pseudocode, description. You can publish this information in this issue, or by private mail to jolive@whitecatboard.org.

**Comment by thunderWhitecat** [comment]
Requested info where not provided.
Please, reopen the issue if anyone can give additions information.
