### ISSUE TITLE
esp8266 support?

### ISSUE THREAD

**Issue by arrowcircle** [whitecatboard/Lua-RTOS-ESP32#203]
Hi!
Readme says Lua RTOS ESP32 support esp8266, but there are no boards available while flashing with wcc tool.
Is esp8266 supported?

**Comment by technomancy** [comment]
Would be great to either fix the readme if it's inaccurate or to provide links to an explanation for how to use the ESP8266.

**Comment by solarkraft** [comment]
Any updates on this? Would it theoretically be compatible? Has there been a port?

**Comment by hiperiondev** [comment]
Any updates?

**Comment by hiperiondev** [comment]
All patches are for esp32 IDF

**Comment by bhgv** [comment]
esp8266 has too (10x) low memory. there are was early choise for esp8266 but it doesn't work for me. 
i did a fork and remade it to run on low memory and some other features like work with ports extenders as esp8266 has too low pin/ports, small httpd, oled etc. but it's hard to work on so low memory.
if you want a workable kind of lua-rtos-esp8266 you may look to my github repo.

**Comment by thunderWhitecat** [comment]
@arrowcircle, @technomancy, @solarkraft, @hiperiondev, @bhgv,

Dear all,

In the past we migrate some parts of Lua RTOS running in PIC32MZ to ESP8266. This work was used later to create Lua RTOS for ESP32.

Due to the interest in Lua RTOS for ESP8266 we have decided to make repository public again. But there is a lot of work to do, and we need collaborators for it.

You can find the repository here:

https://github.com/whitecatboard/Lua-RTOS-ESP8266

**Comment by bhgv** [comment]
> .. But there is a lot of work to do, and we need collaborators for it.
already working fork. a little remaden. include working edit, web-server, threads (but practically you can run only 1 thread additionally to main. low memory) etc

https://github.com/bhgv/LuOS9p-ESP8266

because esp8266 has too low memory you can't write big progs in Lua. the best - to write your own Lua modules in C and connect/configure them with Lua.
