### ISSUE TITLE
ENC28J60 support?

### ISSUE THREAD

**Issue by gjongenelen** [whitecatboard/Lua-RTOS-ESP32#81]
Is ethernet implemented in LuaRTOS? Can see that 'net' has 'wf', but no 'en'.

**Comment by thunderWhitecat** [comment]
Lua RTOS support for now is with ENC28J60 compatible module. This is done because RMMI needs more pins.

RMMI support will be available in the next weeks.

ENC28J60 was removed temporally due to recent esp-idf changes.

The following commit re-enables ENC28J60 support again:

https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/22aaa899dcf100aced4ec6feb1222c6aa44b12a0

It's mandatory to enable ENC28J60 support in KConfig, under the "Lua RTOS -> Hardware -> SPI Ethernet".

**Comment by gjongenelen** [comment]
Alright, succeeded in compiling with eth_spi enabled. But do you know what wiring to use? Or didn't you test it by yourself?
There is no documentation on connecting the esp32 with enc28j60 as far as I can see.

**Comment by thunderWhitecat** [comment]
Our driver is tested with the Pmod NIC100 module.

The wiki has beed updated with additional information about how to setup an ethernet connection and the proposed connections.

https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/Net-module#comments-about-ethernet
https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/Net-module#ethernet

**Comment by gjongenelen** [comment]
Alright, apparently the ENC28J60 totally different from the ENC424J600, as this one doesn't work. Would it be possible to use a LAN8720? I'm using a ESP32-EVB now and it would be nice to use the onboard ethernet.

**Comment by thunderWhitecat** [comment]
LAN8720 is not planned yet, but it will be available as soon as possible.

**Comment by thunderWhitecat** [comment]
I have ordered some LAN8720 modules for test.

**Comment by gjongenelen** [comment]
You're awesome! Can't wait

**Comment by thunderWhitecat** [comment]
LAN8720 modules for test have arrived today.
Now I'm searching for time for do that ...

**Comment by thunderWhitecat** [comment]
Hi @gjongenelen,

First RMII ethernet support since last commit https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/0d17ca260bafcd921b56fee1bb0664e83d42ebc9

In the following days I will update the wiki.

Tested with LAN8720 module from Waveshare.

In my hardware setup I have a transistor configured as open-collector and activated by GPIO2 as power pin. Emitter to GND. Collector to LAN8720 GND. This is required to avoid problems on GPIO0 when board is started.

**Comment by gjongenelen** [comment]
Alright, will try today!

**Comment by thunderWhitecat** [comment]
Proposed connections:

![image](https://user-images.githubusercontent.com/16651312/32322487-f57e6dba-bfc4-11e7-903d-d8a76160936a.png)

**Comment by gjongenelen** [comment]
I'm still tying to figure out my pin mapping from this example https://github.com/OLIMEX/ESP32-EVB/tree/master/SOFTWARE/ETH_PHY_demo

**Comment by thunderWhitecat** [comment]
Yes, but it's not enougth to power on the module during the reset, and requires to make hardware mods on the lan module. You need to have all the lan module pins in hi-impedance state in the boot phase.

**Comment by thunderWhitecat** [comment]
We close this issue, because we have not feedback from you. Please, reopen it if you need more assistance.

For your information LAN8720 RMII support has been successfully tested in Olimex ESP32-GATEWAY and Olimex ESP32-EVB boards, that since yesterday are supported by Lua RTOS.

**Comment by thunderWhitecat** [comment]
Hi @gjongenelen,

FYI this will be our next board, a Lora WAN gateway based on ESP32 PICO D4.

https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/Whitecat-ESP32-LORA-GATEWAY

We use a LAN8720A, and chip enabled goes directly to the 50 Mhz oscillator's enabled PIN. It's a more elegant solution that the proposed above.

Also we have test it without oscillator using the ESP32 50 Mhz clock reference on GPIO17 that can be useful in some hardware designs.

Please don't doubt to be in contact if you need more assistance.

**Comment by gjongenelen** [comment]
That looks fantastic! When do you expect to release it? Do you know anything about the retail price?
